name: build-and-lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build backend image
        run: docker build -t backend ./server

      - name: Build frontend image
        run: docker build -t frontend ./client

  # Deploy job is intentionally disabled for Part 2 (no active EC2)
  deploy:
    needs: build-and-lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Skip deployment (EC2 disabled for Part 2 demo)
        run: |
          echo "---------------------------------------"
          echo "Deployment step is disabled in this demo repository."
          echo "This pipeline runs build-and-lint so you can continue Part 2 work."
          echo "To re-enable EC2 deployment, restore the original deploy steps and add EC2 secrets."
          echo "---------------------------------------"
